__title__ = "Quart-Login"
__description__ = "User session management for Quart"
__url__ = "https://github.com/jamiejackherer/quart-login"
__version_info__ = ("0", "7", "0")
__version__ = ".".join(__version_info__)
__author__ = "Jamie Lindsey"
__author_email__ = "jamieoglindsey0@gmail.com"
__maintainer__ = "Jamie Lindsey"
__license__ = "MIT"
__copyright__ = "(c) 2022 by Jamie Lindsey"
